import HeaderBanner from "./components/HeaderBanner";
import Nav from "./components/Nav";
import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={roboto.className}
    >
      <body>
        <header>
          <HeaderBanner />
          <Nav />
        </header>
        {children}
      </body>
    </html>
  );
}
